version: "3.7"

services:
  app :
    build:
      context: .
    volumes:
      - ./dist:/app
    restart: on-failure
    command: ["java","-jar","synergyway-0.0.1-SNAPSHOT.jar"]

  db:
    image: mysql:8.0
    env_file:
      - .env.db
    restart: always

    volumes:
      - ./mysql:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - app
    restart: on-failure
    volumes:
    - ./client:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

